apiVersion: apps/v1 
kind: Deployment
metadata:
  name: first-deployment
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: httpd:latest
        name: apache
        command:
          #- /bin/bash
          #- "-c"
          #- "sleep 60m"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always